Add section on smart nested field
marshmallow-code/marshmallow-sqlalchemy pull request #111
Opened 2017-06-10 13:50 UTC by ilya-chistyakov

This is a small recipe for improving the nested field. I spent a lot of energy to find a place where I can do this trick. I think this is a common problem for rest api.

2017-06-13 01:15 UTC, sloria requested changes
Thanks for the contribution! This is a neat recipe. Just a few revisions, and this is will be good to merge.

2017-06-13 01:15 UTC, sloria commented on docs/recipes.rst
> +            if attr not in obj.__dict__:
Why not use `hasattr`?

2017-06-13 01:15 UTC, sloria commented on docs/recipes.rst
> +======================================================
The underline should be the same length as the title; otherwise Sphinx will raise a warning.

2017-06-13 01:15 UTC, sloria commented on docs/recipes.rst
> +If you want to avoid lazy loading a nested attribute, but you still need id, then use this trick.
How about revising this to:

"To serialize nested attributes to primary keys unless they are already loaded, you can use this custom field."

2017-06-13 01:15 UTC, sloria commented on docs/recipes.rst
> +This method allows you to make convenient rest api, where relationship id will always be in one place.
This sentence is unnecessary; omit.

2017-06-13 02:39 UTC, ilya-chistyakov commented on docs/recipes.rst
> +            if attr not in obj.__dict__:
This lazy attribute always exists. So I need to test this in a different way.

2017-06-13 04:48 UTC, sloria commented on docs/recipes.rst
> +            if attr not in obj.__dict__:
Ah ok, thanks for the clarification.

2017-06-13 11:59 UTC, sloria commented on docs/recipes.rst
> +If you want to avoid lazy loading a nested attribute, but you still need id, then use this trick.
Also, I believe there needs to be an empty line between the header and this text in order to be rendered correctly.

2017-06-14 00:20 UTC, sloria approved these changes

2017-06-14 00:20 UTC, merged

2017-06-14 00:23 UTC, sloria commented
Thanks!