Allow getting session from the context.
marshmallow-code/marshmallow-sqlalchemy pull request #129
Opened 2018-05-27 17:23 UTC by gtxm

Hey,

Sometimes you are not able to provide the session to the Meta class and you want to mix marshmallow schema with marshmallow-sqlalchemy. The only place where you can put the session is the context (but you do it is up to you). With this PR you can override the session property to include session from context (example included in tests).

Cheers

2018-05-28 18:08 UTC, sloria requested changes
Thanks for the PR! Just one comment to address, and this should be good to merge.

2018-05-28 18:08 UTC, sloria commented on marshmallow_sqlalchemy/schema.py
> +        return self._session or self.opts.sqla_session
This is a breaking change since `session` was a public, write-able attribute. Adding a `setter` should make this backwards-compatible.

2018-05-28 19:55 UTC, gtxm commented
Hey, thanks for the comment, I forgot about it, now it should be ok. :smile:

2018-05-29 02:11 UTC, sloria approved these changes

2018-05-29 02:11 UTC, merged