Allow to override field kwargs and model layer
marshmallow-code/marshmallow-sqlalchemy pull request #133
Opened 2018-07-25 07:31 UTC by jeanphix

e.g.:

```python
    class Book(Model):
        # ...

        abstract = Column(
            Text(),
            info=dict(
                schema=dict(required=True),
            ),
        )
```

2018-11-04 18:10 UTC, sloria requested changes
Thanks for the PR! Just a few small suggestions.

2018-11-04 18:10 UTC, sloria commented on docs/recipes.rst
> +                schema=dict(required=True),
Not sure about "schema"; it seems too general. #22 uses "marshmallow_sqlalchemy", which is more explicit, but verbose. How about "marshmallow"?

2018-11-04 18:10 UTC, sloria commented on marshmallow_sqlalchemy/convert.py
> +            # Ensure we do not override the generated validators.
I'm confused by this comment. Doesn't the `_merge_validators` method ensure that the validators passed in `info` *do* override the generated validators?

2018-11-04 18:10 UTC, sloria commented on docs/recipes.rst
> +Alternatively `SQLAlchemy SchemaItem.info` can be used to override field initialization:
Minor revision suggestion:

```suggestion
You can customize the keyword arguments passed to a column property's corresponding marshmallow field by passing the ``info`` argument to the `Column`.
```

2018-11-04 18:11 UTC, sloria commented
@jeanphix Can you also update this with `dev` when you get the chance? That should fix the failing builds.

2018-11-04 20:16 UTC, jeanphix commented
Fixed and rebased.

2018-11-04 20:25 UTC, sloria commented on marshmallow_sqlalchemy/convert.py
> +    def _merge_validators(self, defaults, new):
Not necessarily a blocker to merging, but it would be good to have a test for this merging behavior. For example, what happens when a column sets a `length` but a `Length` validator is passed to `info.marshmallow`?

2018-11-04 20:28 UTC, sloria commented
Thanks @jeanphix for updating this. Just one more suggestion about testing the validator merging. Let me know if you don't have time to do it right now. It can be done in a follow-up PR if need be.

2018-11-05 06:00 UTC, jeanphix commented on marshmallow_sqlalchemy/convert.py
> +    def _merge_validators(self, defaults, new):
Then the Length from `info.marshmallow` is the considered one.

It just prevents from bulk replacing the `validate[]` collection.

2018-11-05 06:01 UTC, jeanphix commented
Done.

2018-11-05 06:07 UTC, jeanphix commented on marshmallow_sqlalchemy/convert.py
> +    def _merge_validators(self, defaults, new):
Then it's the one from `info.marshmallow`.

2018-11-05 13:09 UTC, sloria approved these changes

2018-11-05 13:09 UTC, merged

2018-11-05 13:09 UTC, sloria commented
Thanks!

2018-11-05 13:12 UTC, jeanphix commented
You're welcome :)

Think you could bump a release ?

2018-11-05 13:22 UTC, sloria commented
Yes, this is released in 0.15.0.

2018-11-05 13:23 UTC, sloria commented
By the way, I'm starting to use something along the lines of the [Pull Request Hack](http://felixge.de/2013/03/11/the-pull-request-hack.html). Basically, if you get a PR merged in, you get an invite to have commit access.

No pressure to do any more work than you already have. Just want to open the door to further collaboration. =)

2018-11-15 16:14 UTC, cancan101 commented
I'm here a little late to this, but it seems like this mixes view (schema) and model concepts: namely specifying schema behavior on the model. Why not (at this point in addition to this change) do what DRF does and allow loading extra kwargs for the schema from the schema's meta: https://www.django-rest-framework.org/api-guide/serializers/#additional-keyword-arguments

2018-11-15 16:21 UTC, jeanphix commented
The idea here was mainly to have a single declarative layer.

But yes, maybe a nice improvement to add a `Meta.extra_kwargs`, it could help when dealing with reflected models.